// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260129223831_SeedEstatus")]
    partial class SeedEstatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Identity.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("DataAccess.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("CantidadHijos")
                        .HasColumnType("int")
                        .HasColumnName("cantidadHijos");

                    b.Property<string>("Cedula")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("cedula");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoEmpresa")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("correoEmpresa");

                    b.Property<string>("CorreoPersonal")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("correoPersonal");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaNacimiento");

                    b.Property<bool>("Hijos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("hijos");

                    b.Property<DateTime?>("LastActivityUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("lastActivityUtc");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NoEmpleado")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("noEmpleado");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PrimerApellido")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("primerApellido");

                    b.Property<string>("PrimerNombre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("primerNombre");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SegundoApellido")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("segundoApellido");

                    b.Property<string>("SegundoNombre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("segundoNombre");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sessionId");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Cedula")
                        .IsUnique()
                        .HasFilter("[cedula] IS NOT NULL");

                    b.HasIndex("CorreoEmpresa")
                        .IsUnique()
                        .HasFilter("[correoEmpresa] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.Attachment", b =>
                {
                    b.Property<int>("IdAttachment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idAttachment");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAttachment"));

                    b.Property<int?>("ComentarioIdComentario")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fileName");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("filePath");

                    b.Property<double>("FileSize")
                        .HasColumnType("float")
                        .HasColumnName("fileSize");

                    b.Property<int?>("IdComentario")
                        .HasColumnType("int")
                        .HasColumnName("idComentario");

                    b.Property<int>("IdTiquete")
                        .HasColumnType("int")
                        .HasColumnName("idTiquete");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mimeType");

                    b.Property<int?>("TiqueteIdTiquete")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("uploadedAt");

                    b.Property<int>("UploadedBy")
                        .HasColumnType("int")
                        .HasColumnName("uploadedBy");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdAttachment");

                    b.HasIndex("ComentarioIdComentario");

                    b.HasIndex("TiqueteIdTiquete");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ATTACHMENT");
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idCategoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombreCategoria");

                    b.HasKey("IdCategoria");

                    b.ToTable("CATEGORIA");
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.Cola", b =>
                {
                    b.Property<int>("IdCola")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idCola");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCola"));

                    b.Property<int?>("CategoriaIdCategoria")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("createdBy");

                    b.Property<string>("DescripcionCola")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcionCola");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<string>("NombreCola")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombreCola");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("idCategoria")
                        .HasColumnType("int")
                        .HasColumnName("idCategoria");

                    b.HasKey("IdCola");

                    b.HasIndex("CategoriaIdCategoria");

                    b.HasIndex("UsuarioId");

                    b.ToTable("COLA");
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.Comentario", b =>
                {
                    b.Property<int>("IdComentario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idComentario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdComentario"));

                    b.Property<string>("AutorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("IdAutor")
                        .HasColumnType("int")
                        .HasColumnName("idAutor");

                    b.Property<int>("IdTiquete")
                        .HasColumnType("int")
                        .HasColumnName("idTiquete");

                    b.Property<int>("TiqueteIdTiquete")
                        .HasColumnType("int");

                    b.Property<string>("createdAt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("createdAt");

                    b.Property<int>("textoComentario")
                        .HasColumnType("int")
                        .HasColumnName("textoComentario");

                    b.HasKey("IdComentario");

                    b.HasIndex("AutorId");

                    b.HasIndex("TiqueteIdTiquete");

                    b.ToTable("COMENTARIO");
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.Estatus", b =>
                {
                    b.Property<int>("IdEstatus")
                        .HasColumnType("int")
                        .HasColumnName("idEstatus");

                    b.Property<string>("NombreEstatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombreEstatus");

                    b.HasKey("IdEstatus");

                    b.ToTable("Estatus");

                    b.HasData(
                        new
                        {
                            IdEstatus = 1,
                            NombreEstatus = "Abierto"
                        },
                        new
                        {
                            IdEstatus = 2,
                            NombreEstatus = "En Progreso"
                        },
                        new
                        {
                            IdEstatus = 3,
                            NombreEstatus = "Cancelado"
                        },
                        new
                        {
                            IdEstatus = 4,
                            NombreEstatus = "Resuelto"
                        },
                        new
                        {
                            IdEstatus = 5,
                            NombreEstatus = "Cerrado"
                        });
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.Prioridad", b =>
                {
                    b.Property<int>("IdPrioridad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idPrioridad");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrioridad"));

                    b.Property<string>("NombrePrioridad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombrePrioridad");

                    b.HasKey("IdPrioridad");

                    b.ToTable("PRIORIDAD");
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.Tiquete", b =>
                {
                    b.Property<int>("IdTiquete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idTiquete");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTiquete"));

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("asunto");

                    b.Property<int>("CategoriaIdCategoria")
                        .HasColumnType("int");

                    b.Property<int?>("ColaIdCola")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<int>("EstatusIdEstatus")
                        .HasColumnType("int");

                    b.Property<string>("IdAsignee")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("idAsignee");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("idCategoria");

                    b.Property<int>("IdCola")
                        .HasColumnType("int")
                        .HasColumnName("idCola");

                    b.Property<int>("IdEstatus")
                        .HasColumnType("int")
                        .HasColumnName("idEstatus");

                    b.Property<int>("IdPrioridad")
                        .HasColumnType("int")
                        .HasColumnName("idPrioridad");

                    b.Property<string>("IdReportedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("idReportedBy");

                    b.Property<int?>("PrioridadIdPrioridad")
                        .HasColumnType("int");

                    b.Property<string>("Resolucion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("resolucion");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedAt");

                    b.HasKey("IdTiquete");

                    b.HasIndex("CategoriaIdCategoria");

                    b.HasIndex("ColaIdCola");

                    b.HasIndex("EstatusIdEstatus");

                    b.HasIndex("IdAsignee");

                    b.HasIndex("IdReportedBy");

                    b.HasIndex("PrioridadIdPrioridad");

                    b.ToTable("TIQUETE");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.Attachment", b =>
                {
                    b.HasOne("DataAccess.Modelos.Entidades.Comentario", "Comentario")
                        .WithMany()
                        .HasForeignKey("ComentarioIdComentario");

                    b.HasOne("DataAccess.Modelos.Entidades.Tiquete", "Tiquete")
                        .WithMany("Attachments")
                        .HasForeignKey("TiqueteIdTiquete");

                    b.HasOne("DataAccess.Identity.ApplicationUser", "Usuario")
                        .WithMany("Attachments")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Comentario");

                    b.Navigation("Tiquete");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.Cola", b =>
                {
                    b.HasOne("DataAccess.Modelos.Entidades.Categoria", "Categoria")
                        .WithMany("Cola")
                        .HasForeignKey("CategoriaIdCategoria");

                    b.HasOne("DataAccess.Identity.ApplicationUser", "Usuario")
                        .WithMany("Colas")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.Comentario", b =>
                {
                    b.HasOne("DataAccess.Identity.ApplicationUser", "Autor")
                        .WithMany("Comentarios")
                        .HasForeignKey("AutorId");

                    b.HasOne("DataAccess.Modelos.Entidades.Tiquete", "Tiquete")
                        .WithMany("Comentarios")
                        .HasForeignKey("TiqueteIdTiquete")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Tiquete");
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.Tiquete", b =>
                {
                    b.HasOne("DataAccess.Modelos.Entidades.Categoria", "Categoria")
                        .WithMany("Tiquete")
                        .HasForeignKey("CategoriaIdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Modelos.Entidades.Cola", "Cola")
                        .WithMany("Tiquete")
                        .HasForeignKey("ColaIdCola");

                    b.HasOne("DataAccess.Modelos.Entidades.Estatus", "Estatus")
                        .WithMany("Tiquete")
                        .HasForeignKey("EstatusIdEstatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Identity.ApplicationUser", "Asignee")
                        .WithMany("TiquetesAsignados")
                        .HasForeignKey("IdAsignee")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataAccess.Identity.ApplicationUser", "ReportedBy")
                        .WithMany("TiquetesReportados")
                        .HasForeignKey("IdReportedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccess.Modelos.Entidades.Prioridad", "Prioridad")
                        .WithMany("Tiquete")
                        .HasForeignKey("PrioridadIdPrioridad");

                    b.Navigation("Asignee");

                    b.Navigation("Categoria");

                    b.Navigation("Cola");

                    b.Navigation("Estatus");

                    b.Navigation("Prioridad");

                    b.Navigation("ReportedBy");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("DataAccess.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DataAccess.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DataAccess.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("DataAccess.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DataAccess.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccess.Identity.ApplicationUser", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Colas");

                    b.Navigation("Comentarios");

                    b.Navigation("TiquetesAsignados");

                    b.Navigation("TiquetesReportados");
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.Categoria", b =>
                {
                    b.Navigation("Cola");

                    b.Navigation("Tiquete");
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.Cola", b =>
                {
                    b.Navigation("Tiquete");
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.Estatus", b =>
                {
                    b.Navigation("Tiquete");
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.Prioridad", b =>
                {
                    b.Navigation("Tiquete");
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.Tiquete", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Comentarios");
                });
#pragma warning restore 612, 618
        }
    }
}
