// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260313062020_CrearMantenimientoActivo")]
    partial class CrearMantenimientoActivo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Identity.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("DataAccess.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("CantidadHijos")
                        .HasColumnType("int")
                        .HasColumnName("cantidadHijos");

                    b.Property<string>("Cedula")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("cedula");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoEmpresa")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("correoEmpresa");

                    b.Property<string>("CorreoPersonal")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("correoPersonal");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CreatedById")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("Departamento")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("departamento");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaNacimiento");

                    b.Property<bool>("Hijos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("hijos");

                    b.Property<DateTime?>("LastActivityUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("lastActivityUtc");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NoEmpleado")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("noEmpleado");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PrimerApellido")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("primerApellido");

                    b.Property<string>("PrimerNombre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("primerNombre");

                    b.Property<string>("Puesto")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("puesto");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SegundoApellido")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("segundoApellido");

                    b.Property<string>("SegundoNombre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("segundoNombre");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sessionId");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("UserName");

                    b.HasKey("Id");

                    b.HasIndex("Cedula")
                        .IsUnique()
                        .HasFilter("[cedula] IS NOT NULL");

                    b.HasIndex("CorreoEmpresa")
                        .IsUnique()
                        .HasFilter("[correoEmpresa] IS NOT NULL");

                    b.HasIndex("CreatedById");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.Auditoria", b =>
                {
                    b.Property<int>("idAudit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idAudit");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idAudit"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("accion");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("time")
                        .HasColumnName("hora");

                    b.Property<string>("Tabla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tabla");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("usuario");

                    b.HasKey("idAudit");

                    b.ToTable("Auditoria");
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.Autenticacion.IntentoInicioSesion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("EmailIngresado")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("Exitoso")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("MotivoFallo")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("IntentoInicioSesion", (string)null);
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.Integracion.IntegracionHistorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DetalleError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("FilasConError")
                        .HasColumnType("int");

                    b.Property<int>("FilasValidas")
                        .HasColumnType("int");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoProceso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalFilas")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioEjecutorId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IntegracionHistorial");
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.Inventario.ActivoInventario", b =>
                {
                    b.Property<int>("IdActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdActivo"));

                    b.Property<string>("ClaveLicencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionMAC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEstadoActivo")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoActivo")
                        .HasColumnType("int");

                    b.Property<int?>("IdTipoLicencia")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreMaquina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroActivo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("SerieServicio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SistemaOperativo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioActualId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioAnteriorId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdActivo");

                    b.HasIndex("IdEstadoActivo");

                    b.HasIndex("IdTipoActivo");

                    b.HasIndex("IdTipoLicencia");

                    b.HasIndex("NumeroActivo")
                        .IsUnique();

                    b.ToTable("ActivoInventario", (string)null);
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.Inventario.ActivoInventarioTiquete", b =>
                {
                    b.Property<int>("IdActivoInventarioTiquete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdActivoInventarioTiquete"));

                    b.Property<DateTime>("FechaAsociacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdActivo")
                        .HasColumnType("int");

                    b.Property<int>("IdTiquete")
                        .HasColumnType("int");

                    b.HasKey("IdActivoInventarioTiquete");

                    b.HasIndex("IdTiquete");

                    b.HasIndex("IdActivo", "IdTiquete")
                        .IsUnique();

                    b.ToTable("ActivoInventarioTiquete", (string)null);
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.Inventario.EstadoActivoInventario", b =>
                {
                    b.Property<int>("IdEstadoActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoActivo"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("IdEstadoActivo");

                    b.ToTable("EstadoActivoInventario", (string)null);
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.Inventario.MantenimientoActivo", b =>
                {
                    b.Property<int>("IdMantenimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMantenimiento"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaMantenimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdActivo")
                        .HasColumnType("int");

                    b.Property<string>("TipoMantenimiento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdMantenimiento");

                    b.HasIndex("IdActivo");

                    b.ToTable("MantenimientoActivo", (string)null);
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.Inventario.TipoActivoInventario", b =>
                {
                    b.Property<int>("IdTipoActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoActivo"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("IdTipoActivo");

                    b.ToTable("TipoActivoInventario", (string)null);
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.Inventario.TipoLicenciaInventario", b =>
                {
                    b.Property<int>("IdTipoLicencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoLicencia"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("IdTipoLicencia");

                    b.ToTable("TipoLicenciaInventario", (string)null);
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.InventarioTelefono.ActivoTelefono", b =>
                {
                    b.Property<int>("IdActivoTelefono")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdTelefono");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdActivoTelefono"));

                    b.Property<bool>("Auriculares")
                        .HasColumnType("bit");

                    b.Property<bool>("Cargador")
                        .HasColumnType("bit");

                    b.Property<string>("CorreoSistemasAnaliticos")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Departamento")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("IMEI")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreColaborador")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NumeroCelular")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Operador")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdActivoTelefono");

                    b.ToTable("ActivoTelefono");
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.ModTiquete.Attachment", b =>
                {
                    b.Property<int>("IdAttachment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idAttachment");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAttachment"));

                    b.Property<byte[]>("File")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("file");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fileName");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("fileSize");

                    b.Property<int>("IdTiquete")
                        .HasColumnType("int")
                        .HasColumnName("idTiquete");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("uploadedAt");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("uploadedBy");

                    b.HasKey("IdAttachment");

                    b.HasIndex("IdTiquete");

                    b.HasIndex("UploadedBy");

                    b.ToTable("Attachment");
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.ModTiquete.Avance", b =>
                {
                    b.Property<int>("IdAvance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idAvance");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAvance"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<string>("IdAutor")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("idAutor");

                    b.Property<int>("IdTiquete")
                        .HasColumnType("int")
                        .HasColumnName("idTiquete");

                    b.Property<string>("TextoAvance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("textoAvance");

                    b.HasKey("IdAvance");

                    b.HasIndex("IdAutor");

                    b.HasIndex("IdTiquete");

                    b.ToTable("Avance", t =>
                        {
                            t.HasTrigger("TR_Avance_Insert_Notificacion");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.ModTiquete.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idCategoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombreCategoria");

                    b.HasKey("IdCategoria");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.ModTiquete.Estatus", b =>
                {
                    b.Property<int>("IdEstatus")
                        .HasColumnType("int")
                        .HasColumnName("idEstatus");

                    b.Property<string>("NombreEstatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombreEstatus");

                    b.HasKey("IdEstatus");

                    b.ToTable("Estatus");

                    b.HasData(
                        new
                        {
                            IdEstatus = 1,
                            NombreEstatus = "Creado"
                        },
                        new
                        {
                            IdEstatus = 2,
                            NombreEstatus = "En Proceso"
                        },
                        new
                        {
                            IdEstatus = 3,
                            NombreEstatus = "En Espera Del Usuario"
                        },
                        new
                        {
                            IdEstatus = 4,
                            NombreEstatus = "Cancelado"
                        },
                        new
                        {
                            IdEstatus = 5,
                            NombreEstatus = "Resuelto"
                        });
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.ModTiquete.Prioridad", b =>
                {
                    b.Property<int>("IdPrioridad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idPrioridad");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrioridad"));

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int")
                        .HasColumnName("duracionMinutos");

                    b.Property<string>("NombrePrioridad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombrePrioridad");

                    b.HasKey("IdPrioridad");

                    b.ToTable("Prioridad");
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.ModTiquete.SubCategoria", b =>
                {
                    b.Property<int>("IdSubCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idSubCategoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSubCategoria"));

                    b.Property<int?>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("idCategoria");

                    b.Property<int?>("IdPrioridad")
                        .HasColumnType("int")
                        .HasColumnName("idPrioridad");

                    b.Property<string>("NombreSubCategoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombreSubCategoria");

                    b.HasKey("IdSubCategoria");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdPrioridad");

                    b.ToTable("SubCategoria");
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.ModTiquete.Tiquete", b =>
                {
                    b.Property<int>("IdTiquete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idTiquete");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTiquete"));

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("asunto");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<string>("Departamento")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("departamento");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<string>("IdAsignee")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("idAsignee");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("idCategoria");

                    b.Property<int>("IdEstatus")
                        .HasColumnType("int")
                        .HasColumnName("idEstatus");

                    b.Property<string>("IdReportedBy")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("idReportedBy");

                    b.Property<int>("OrdenCola")
                        .HasColumnType("int")
                        .HasColumnName("ordenCola");

                    b.Property<string>("Resolucion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("resolucion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("updatedBy");

                    b.HasKey("IdTiquete");

                    b.HasIndex("IdAsignee");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdEstatus");

                    b.HasIndex("IdReportedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Tiquete", t =>
                        {
                            t.HasTrigger("TR_Tiquete_Insert_Notificacion");

                            t.HasTrigger("TR_Tiquete_Update_Notificacion");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.ModTiquete.TiqueteHistorial", b =>
                {
                    b.Property<int>("IdHistorial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idHistorial");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistorial"));

                    b.Property<string>("CampoAfectado")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("campoAfectado");

                    b.Property<string>("DescripcionEvento")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcionEvento");

                    b.Property<int>("IdTiquete")
                        .HasColumnType("int")
                        .HasColumnName("idTiquete");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("performedAt");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("performedBy");

                    b.Property<int>("TipoEvento")
                        .HasColumnType("int")
                        .HasColumnName("tipoEvento");

                    b.Property<string>("ValorAnterior")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("valorAnterior");

                    b.Property<string>("ValorNuevo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("valorNuevo");

                    b.HasKey("IdHistorial");

                    b.HasIndex("IdTiquete");

                    b.HasIndex("PerformedBy");

                    b.ToTable("TiqueteHistorial");
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.Notificacion", b =>
                {
                    b.Property<long>("IdNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("idNotificacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdNotificacion"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaCreacion");

                    b.Property<int>("IdTiquete")
                        .HasColumnType("int")
                        .HasColumnName("idTiquete");

                    b.Property<bool>("Leida")
                        .HasColumnType("bit")
                        .HasColumnName("leida");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("mensaje");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tipoEvento");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UserId");

                    b.HasKey("IdNotificacion");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.NotificacionSilencio", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("idTiquete")
                        .HasColumnType("int");

                    b.Property<DateTime>("fechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaFin")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "idTiquete", "fechaInicio");

                    b.ToTable("NotificacionSilencio");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DataAccess.Identity.ApplicationUser", b =>
                {
                    b.HasOne("DataAccess.Identity.ApplicationUser", "CreatedByUser")
                        .WithMany("UsersCreated")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.Autenticacion.IntentoInicioSesion", b =>
                {
                    b.HasOne("DataAccess.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.Inventario.ActivoInventario", b =>
                {
                    b.HasOne("DataAccess.Modelos.Entidades.Inventario.EstadoActivoInventario", "EstadoActivo")
                        .WithMany()
                        .HasForeignKey("IdEstadoActivo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Modelos.Entidades.Inventario.TipoActivoInventario", "TipoActivo")
                        .WithMany()
                        .HasForeignKey("IdTipoActivo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Modelos.Entidades.Inventario.TipoLicenciaInventario", "TipoLicencia")
                        .WithMany()
                        .HasForeignKey("IdTipoLicencia");

                    b.Navigation("EstadoActivo");

                    b.Navigation("TipoActivo");

                    b.Navigation("TipoLicencia");
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.Inventario.ActivoInventarioTiquete", b =>
                {
                    b.HasOne("DataAccess.Modelos.Entidades.Inventario.ActivoInventario", "Activo")
                        .WithMany()
                        .HasForeignKey("IdActivo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Modelos.Entidades.ModTiquete.Tiquete", "Tiquete")
                        .WithMany()
                        .HasForeignKey("IdTiquete")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activo");

                    b.Navigation("Tiquete");
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.Inventario.MantenimientoActivo", b =>
                {
                    b.HasOne("DataAccess.Modelos.Entidades.Inventario.ActivoInventario", "Activo")
                        .WithMany()
                        .HasForeignKey("IdActivo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activo");
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.ModTiquete.Attachment", b =>
                {
                    b.HasOne("DataAccess.Modelos.Entidades.ModTiquete.Tiquete", "Tiquete")
                        .WithMany("Attachments")
                        .HasForeignKey("IdTiquete")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Identity.ApplicationUser", "Usuario")
                        .WithMany("Attachments")
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tiquete");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.ModTiquete.Avance", b =>
                {
                    b.HasOne("DataAccess.Identity.ApplicationUser", "Autor")
                        .WithMany("Avances")
                        .HasForeignKey("IdAutor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Modelos.Entidades.ModTiquete.Tiquete", "Tiquete")
                        .WithMany("Avances")
                        .HasForeignKey("IdTiquete")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Tiquete");
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.ModTiquete.SubCategoria", b =>
                {
                    b.HasOne("DataAccess.Modelos.Entidades.ModTiquete.Categoria", "Categoria")
                        .WithMany("SubCategorias")
                        .HasForeignKey("IdCategoria");

                    b.HasOne("DataAccess.Modelos.Entidades.ModTiquete.Prioridad", "Prioridad")
                        .WithMany("SubCategorias")
                        .HasForeignKey("IdPrioridad");

                    b.Navigation("Categoria");

                    b.Navigation("Prioridad");
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.ModTiquete.Tiquete", b =>
                {
                    b.HasOne("DataAccess.Identity.ApplicationUser", "Asignee")
                        .WithMany("TiquetesAsignados")
                        .HasForeignKey("IdAsignee")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataAccess.Modelos.Entidades.ModTiquete.Categoria", "Categoria")
                        .WithMany("Tiquete")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Modelos.Entidades.ModTiquete.Estatus", "Estatus")
                        .WithMany("Tiquete")
                        .HasForeignKey("IdEstatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Identity.ApplicationUser", "ReportedBy")
                        .WithMany("TiquetesReportados")
                        .HasForeignKey("IdReportedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataAccess.Identity.ApplicationUser", "UpdatedByUser")
                        .WithMany("TiquetesEditados")
                        .HasForeignKey("UpdatedBy");

                    b.Navigation("Asignee");

                    b.Navigation("Categoria");

                    b.Navigation("Estatus");

                    b.Navigation("ReportedBy");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.ModTiquete.TiqueteHistorial", b =>
                {
                    b.HasOne("DataAccess.Modelos.Entidades.ModTiquete.Tiquete", "Tiquete")
                        .WithMany("TiqueteHistoriales")
                        .HasForeignKey("IdTiquete")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Identity.ApplicationUser", "User")
                        .WithMany("TiqueteHistoriales")
                        .HasForeignKey("PerformedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tiquete");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("DataAccess.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DataAccess.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DataAccess.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("DataAccess.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DataAccess.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccess.Identity.ApplicationUser", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Avances");

                    b.Navigation("TiqueteHistoriales");

                    b.Navigation("TiquetesAsignados");

                    b.Navigation("TiquetesEditados");

                    b.Navigation("TiquetesReportados");

                    b.Navigation("UsersCreated");
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.ModTiquete.Categoria", b =>
                {
                    b.Navigation("SubCategorias");

                    b.Navigation("Tiquete");
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.ModTiquete.Estatus", b =>
                {
                    b.Navigation("Tiquete");
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.ModTiquete.Prioridad", b =>
                {
                    b.Navigation("SubCategorias");
                });

            modelBuilder.Entity("DataAccess.Modelos.Entidades.ModTiquete.Tiquete", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Avances");

                    b.Navigation("TiqueteHistoriales");
                });
#pragma warning restore 612, 618
        }
    }
}
